version: '3'
services:
  murkel:
    image: ghcr.io/relativity74205/murkelhausen_app/murkel_app:1.12.1
    container_name: murkelhausen
    restart: always
    ports:
      - "80:8000"
    hostname: murkel
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - DJANGO__SECRET_KEY=${DJANGO__SECRET_KEY}
      - DJANGO__DEBUG=${DJANGO__DEBUG}
      - DJANGO__ALLOWED_HOSTS=${DJANGO__ALLOWED_HOSTS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}