version: '3'
services:
  murkel:
    image: ghcr.io/relativity74205/murkelhausen_app/murkel_app:1.15.1
    container_name: murkelhausen
    restart: always
    ports:
      - "8002:8000"
    hostname: murkel
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - DJANGO__SECRET_KEY=${DJANGO__SECRET_KEY}
      - DJANGO__DEBUG=${DJANGO__DEBUG}
      - DJANGO__ALLOWED_HOSTS=${DJANGO__ALLOWED_HOSTS}
      - PI_HOLE_TOKEN=${PI_HOLE_TOKEN}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - PODCASTINDEX_API_SECRET=${PODCASTINDEX_API_SECRET}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}