version: '3'
services:
  murkel:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    hostname: murkel
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - DJANGO__SECRET_KEY=${DJANGO__SECRET_KEY}
      - DJANGO__DEBUG=${DJANGO__DEBUG}
