# Generated by Django 4.2.5 on 2023-09-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0002_vokabel_created_vokabel_updated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vokabel",
            unique_together={("deutsch",)},
        ),
        migrations.CreateModel(
            name="VokabelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "unique_together": {("name",)},
            },
        ),
        migrations.AddField(
            model_name="vokabel",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trainer.vokabelgroup",
            ),
        ),
    ]
