# Generated by Django 4.2.5 on 2023-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0004_vokabelgroup_created_vokabelgroup_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vokabelgroup",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Diese Gruppe existiert bereits."},
                max_length=256,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vokabel",
            unique_together={("deutsch", "group")},
        ),
    ]
