# Generated by Django 4.2.5 on 2023-09-17 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0006_vokabel_count_correct_vokabel_count_wrong_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vokabel",
            name="count_correct",
        ),
        migrations.RemoveField(
            model_name="vokabel",
            name="count_wrong",
        ),
    ]
