# Generated by Django 4.2.1 on 2023-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommerzbankAuszug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buchungstag", models.DateField()),
                ("wertstellung", models.DateField()),
                ("umsatzart", models.CharField(max_length=256)),
                ("buchungstext", models.CharField(max_length=1024)),
                ("betrag", models.FloatField()),
                ("waehrung", models.CharField(max_length=8)),
                ("IBAN_auftraggeberkonto", models.CharField(max_length=32)),
            ],
        ),
    ]
