# Generated by Django 4.2.1 on 2023-05-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0002_commerzbankcategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommerzbankCategory",
            new_name="StatementCategory",
        ),
        migrations.CreateModel(
            name="StatementKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=256)),
                ("is_regex", models.BooleanField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statements.statementcategory",
                    ),
                ),
            ],
        ),
    ]
