# Generated by Django 4.2.1 on 2023-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0004_rename_commerzbankauszug_commerzbankstatements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementkeyword",
            name="is_regex",
            field=models.BooleanField(default=False),
        ),
    ]
