on: [workflow_dispatch]

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: A tagging job
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semver
        uses: ./.github/actions/semver
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # if next_tag is not set, abort
      - name: Get the next tag
        run: echo "The next tag is ${{ steps.semver.outputs.next_tag }}"
      - name: Get the delta changelog
        run: echo 'The changelog delta is ${{ steps.semver.outputs.changelog_delta }}'
        # TODO: add change to pyproject.toml
        # TODO: add change to docker-compose.yml
      - name: write tag to file for testing
        id: write_tag
        run: |
          echo ${{ steps.semver.outputs.next_tag }} > tag.txt
          echo ${{ steps.semver.outputs.changelog_delta }} > changelog.txt
          git config --local user.email "foo@bar.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "chore: update tag.txt and changelog.txt"
          git push
      - name: Create tag
        uses: actions/github-script@v5
        if: steps.semver.outputs.next_tag != ''
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.next_tag }}',
              sha: context.sha
            })
#      - name: Create Release
#        id: create_release
#        if: steps.semver.outputs.next_tag != ''
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.semver.outputs.next_tag }}
#          # TODO prettify changelog; \n are not interpreted; use markdown in a file?; add What's changed title and a Full Changelog link in footer
#          # **Full Changelog**: https://github.com/Relativity74205/murkelhausen_app/compare/1.1.1...1.1.3
#          body: ${{ steps.semver.outputs.changelog_delta }}
#          draft: false
#          prerelease: false

