on: [push]

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semver
        uses: ./.github/actions/semver
        id: semver
      - name: Get the next tag
        run: echo "The next tag is ${{ steps.semver.outputs.next_tag }}"
      - name: Get the delta changelog
        run: echo "The changelog delta is ${{ steps.semver.outputs.changelog_delta }}"
